Update cmatrix.c
Because of:
cmatrix.c:246:10: error: lvalue required as left operand of assignment
     COLS = win.ws_col;
          ^
cmatrix.c:247:11: error: lvalue required as left operand of assignment
     LINES = win.ws_row;
           ^
cmatrix.c:250:15: error: lvalue required as left operand of assignment
         LINES = 10;
               ^
cmatrix.c:253:14: error: lvalue required as left operand of assignment
         COLS = 10;
              ^
make[1]: *** [Makefile:425: cmatrix.o] Fehler 1